"use client"

import React, { useState } from 'react';
import { generateProjectInsight } from '@/ai/flows/project-insight-generator';
import { Button } from './ui/button';
import { Sparkles, Loader2, Info } from 'lucide-react';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";

interface AIInsightButtonProps {
  projectName: string;
  projectDescription: string;
  projectTags: string[];
}

export const AIInsightButton = ({ projectName, projectDescription, projectTags }: AIInsightButtonProps) => {
  const [insight, setInsight] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  const handleGenerate = async () => {
    setLoading(true);
    try {
      const result = await generateProjectInsight({
        projectName,
        projectDescription,
        projectTags
      });
      setInsight(result.insight);
    } catch (error) {
      console.error("AI Insight generation failed:", error);
    } finally {
      setLoading(false);
    }
  };

  return (
    <Dialog>
      <DialogTrigger asChild>
        <Button 
          variant="outline" 
          size="sm" 
          className="gap-2 text-xs font-headline border-primary/30 hover:border-primary/60"
          onClick={() => { if (!insight) handleGenerate(); }}
        >
          <Sparkles className="h-3.5 w-3.5 text-primary" />
          AI Insight
        </Button>
      </DialogTrigger>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Info className="h-5 w-5 text-primary" />
            Technical Insight: {projectName}
          </DialogTitle>
        </DialogHeader>
        <div className="mt-4 space-y-4">
          {loading ? (
            <div className="flex flex-col items-center justify-center py-10 gap-4 text-muted-foreground">
              <Loader2 className="h-8 w-8 animate-spin text-primary" />
              <p className="text-sm font-medium">Generating intelligent overview...</p>
            </div>
          ) : (
            <div className="p-4 rounded-lg bg-muted/50 border leading-relaxed text-sm">
              {insight || "No insight available."}
            </div>
          )}
          <p className="text-[10px] text-muted-foreground text-center italic">
            Insight generated by Genkit AI based on project technicalities.
          </p>
        </div>
      </DialogContent>
    </Dialog>
  );
};